name: BTC Price Alert

on:
  schedule:
    - cron: "*/5 * * * *"  # every hour (UTC)
  workflow_dispatch:  # allow manual trigger

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Bitcoin alert script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python alerts/btc_hourly_alerts.py
